name: Mekanism build

on:
    push:
        branches: [v10.1-ci]
    workflow_dispatch:
jobs:
    build:
        runs-on: self-hosted

        container:
            image: archlinux
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  java-version: '8'
                  distribution: 'zulu'
            - name: Check Java version
              run: java -version
            - name: Check OS
              run: uname -r
            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@v1
            - run: chmod +x ./gradlew
            - name: Build with Gradle
              run: ./gradlew -Dorg.gradle.jvmargs='-Xmx3G' build
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "1.16-ci"
                  prerelease: false
                  files: build/libs/*.jar
